### ISSUE TITLE
Merge open PR requests from mknx

### ISSUE THREAD

**Issue by ohinckel** [smarthomeNG/smarthome#52]
I just started to create new PR for some of my enhancements implemented in [the old project](https://github.com/mknx/smarthome) and want to know which PR are also interesting. I suggest to list them all in this issue.

Currently interesting PR which should be merged into smarthomeNG:
- [x] CLI Plugin: List items matching a pattern - https://github.com/mknx/smarthome/pull/44 -> https://github.com/smarthomeNG/smarthome/pull/46
- [x] New CLI command: dump - https://github.com/mknx/smarthome/pull/138 -> https://github.com/smarthomeNG/smarthome/pull/48
- [x] Issue 59: Support crontab ranges 'x-y' and 'x/y' - https://github.com/mknx/smarthome/pull/61 -> https://github.com/smarthomeNG/smarthome/pull/49
- [x] Add plugin methods to smarthome - https://github.com/mknx/smarthome/pull/81 -> https://github.com/smarthomeNG/smarthome/pull/50 / implemented in a diferent way
- [x] Remove trigger from items - https://github.com/mknx/smarthome/pull/166 -> https://github.com/smarthomeNG/smarthome/pull/51
- [x] CLI: Scheduler commands - https://github.com/mknx/smarthome/pull/148 -> #103
- [x] New "ld" (log dump) command for CLI - https://github.com/mknx/smarthome/pull/93 -> #103
- [x] CLI Plugin: Allow other plugins to add custom commands - https://github.com/mknx/smarthome/pull/182 -> #103
- [x] Support for multiple KNX Interfaces. - https://github.com/mknx/smarthome/pull/124 (obsoleted by #50, but implementation should be updated)
- [x] Make it possible to attach items to a given plugin - https://github.com/mknx/smarthome/pull/83 -> #53
- [x] Add some tests for lib.config - https://github.com/mknx/smarthome/pull/89 -> merged by @cstrassburg
- [x] Make it possible to match on item attribute and it's value - https://github.com/mknx/smarthome/pull/175 -> #80
- [x] Line continuation in config files - https://github.com/mknx/smarthome/pull/167 -> #81
- [x] iCal plugin: Calendar registry and item configuration - https://github.com/mknx/smarthome/pull/58 -> #84
- [x] Attach logic trigger methods for plugins - https://github.com/mknx/smarthome/pull/142 -> #106 
- [x] Disable / enable logics - https://github.com/mknx/smarthome/pull/137 -> #108
- [x] Be able to change dicts/lists via CLI plugin - https://github.com/mknx/smarthome/pull/165 / #118
- [x] DB API2 support in SmartHome.py used in SQLite plugin - https://github.com/mknx/smarthome/pull/69 -> #131

**Comment by msinn** [comment]
The only PR left is the support for multiple KNX interfaces. 
My question is: Is there an implementation vor it or has it to be done?
Maybe we should close this issue and open a new one for `support for multiple KNX interfaces`, if needed.

**Comment by ohinckel** [comment]
From my side there are two requests still open but not listed here. I'll check if I add them here or just creating new PR. This issue was meant to summarize all the stuff implemented before NG was started.

**Comment by ohinckel** [comment]
The following PRs are currently not listed in this issue:
*  Automatically adjust wait timeout in fader - https://github.com/mknx/smarthome/pull/42 -> not creating PR since `item.py` is currently in a refactoring
*  Configure dictionaries in config files - https://github.com/mknx/smarthome/pull/88 -> not creating new PR since it is not clear if we really want to support conf files any longer

I'll keep the original PRs open and close this issue now.
